apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-k8s-operator-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      name: example-k8s-operator-golang
  template:
    metadata:
      labels:
        name: example-k8s-operator-golang
    spec:
      serviceAccountName: example-k8s-operator-golang
      containers:
        - name: example-k8s-operator-golang
          # Replace this with the built image name
          image: ywjcd90/memcached-operator:v0.0.1
          command:
          - example-k8s-operator-golang
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "example-k8s-operator-golang"
