kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-k8s-operator-golang
subjects:
- kind: ServiceAccount
  name: example-k8s-operator-golang
roleRef:
  kind: Role
  name: example-k8s-operator-golang
  apiGroup: rbac.authorization.k8s.io
